language: node_js
sudo: required
matrix:
  include:
    # This builder checks explorer build
    - os: linux
      dist: xenial
      node_js: '8'
      services:
        - docker
      before_install:
        - docker pull trufflesuite/ganache-cli
        - docker run -d -p 8546:8546 -p 27017:27017 trufflesuite/ganache-cli -p 8546
        - varA=`docker ps --no-trunc -q | cut -c 1-12`
        - docker pull mongo
        - docker run -d --network="container:$varA" mongo
        - docker build -t ethereumclassic/explorer .
        - docker run -d --network="container:$varA" ethereumclassic/explorer app.js
      script:
        - npm run test

    # This builder only tests code linters
    - os: linux
      dist: xenial
      node_js: '8'
      env: lint
      script:
        - npm run lint:check

  # Temporary allow failures for eslint until the code is done.
  allow_failures:
    - env: lint
