version: '3'
services:
  app:
    build: .
    command: ./app.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://db/explorerDB'
    ports:
      - '3000:3000'
    depends_on:
      - db
  sync:
    build: .
    command: ./tools/sync.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  stats:
    build: .
    command: ./tools/stats.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  price:
    build: .
    command: ./tools/price.js
    restart: always
    environment:
      MONGO_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  richlist:
    build: .
    command: ./tools/richlist.js
    restart: "no"
    environment:
      MONGO_URI: 'mongodb://db/explorerDB'
    depends_on:
      - db
  db:
    image: mongo
